#!/bin/bash
#
# By Chih-Wei Huang <cwhuang@linux.org.tw>
# 	 Shadichy <shadichy@blisslabs.org>
# and BlissLabs & Contributors
#
# License: GNU Public License
# We explicitely grant the right to use the scripts
# with Android-x86 project.
#
# shellcheck disable=SC2164,SC1091

export SCRIPT_DIR=/usr/share/scripts

# configure debugging output
LOG=/tmp/log
set -x

[ -f $SCRIPT_DIR/00-ver ] && . $SCRIPT_DIR/00-ver

tempfile=/tmp/temp-$$
menufile=/tmp/menu-$$

BOOT_ID=BassOS
OS_TITLE=${OS_TITLE:-$BOOT_ID}
MIN_PT_SIZE=${MIN_PT_SIZE:-10GB}
DEST=/hd

# Debug shell no longer takes arguments anymore
debug_shell() { bash 2>&1; }

rebooting() {
	dialog --title " Rebooting... " --nocancel --pause "" 8 41 1
	sync && reboot
}

auto_answer() {
	echo "$answer" >$tempfile
	unset answer
	[ "$(cat $tempfile)" != 0 ]
}

set_answer_if_auto() { [ "$OEM_INSTALL" ] && export answer=$1; }

adialog() { if [ "$answer" ]; then auto_answer; else dialog "$@" 2>$tempfile; fi; }

choose() {
	adialog --clear --title " \"$1\" " --menu "$2" 21 79 13 --file $menufile
	RET=$?
	CHOICE=$(cat $tempfile)
	export RET CHOICE
}

size_gb() { printf '%0.2fGB' "$(dc -e"6 k $(cat "$1/size") 2097152 / p")"; }

# check if specified device has pattern like UUID= or LABEL=
find_device() {
	case "$1" in
	UUID=* | LABEL=*) findfs "$1" ;;
	*) echo "$1" ;;
	esac
}

find_partition() { grep -H "^$2$" /sys/block/"$1"/*/partition 2>/dev/null | cut -d/ -f5; }

declare -a LIST_DISK=()

list_disks() {
	# Prioritize internal disks
	declare -a internal=() removable=()
	local b s
	while read -r b; do
		s=$(size_gb "$b")
		if
			: &&
				[ -d "$b" ] &&
				[ ! -d "$b/$BOOTED_FROM" ] &&
				[ "$(cat "$b/ro")" != 1 ] &&
				(("${s%.*}" > "${MIN_PT_SIZE%GB}"))
		then
			if [ "$(cat "$b/removable")" = 1 ]; then
				removable+=("$b")
			elif [ ! "$(blkid "/dev/$(basename "$b")")" ]; then 
			# if device is not filesystem-on-disk (usually flashable USB/CD/DVD boot devices)
				internal+=("$b")
			fi
		fi
	done < <(find /sys/block -mindepth 1 -maxdepth 1 | grep -Ev "loop|ram|sr|boot|rpmb")
	LIST_DISK=("${internal[@]}" "${removable[@]}")
}

# shellcheck disable=SC2068
try_mount() {
	local RW=$1
	shift

	# if already mounted
	grep -q "$1 $2" /proc/mounts && return 0

	if [ "${ROOT#*:/}" != "$ROOT" ]; then
		# for NFS roots, use nolock to avoid dependency to portmapper
		mount -o "$RW",noatime,nolock $@
		return $?
	fi

	case "$(blkid "$1")" in
	*TYPE=*ntfs*)
		echo "WARNING: NTFS may not work well with BlissOS. Consider using another filesystem."
		if [ "$USE_NTFSPLUS" -ge 1 ] || [ "$BOOT_USE_NTFSPLUS" -ge 1 ]; then
			mount -t ntfs -o rw,force $@
		elif [ "$USE_NTFS3" -ge 1 ] || [ "$BOOT_USE_NTFS3" -ge 1 ]; then
			mount -t ntfs3 -o rw,noatime,windows_names $@
		else
			mount.ntfs-3g -o rw,force $@
		fi
		;;
	*TYPE=*) mount -o "$RW",noatime $@ ;;
	*) return 1 ;;
	esac
}

export _LAST_LOOP=0

setup_loop() {
	local base i=$_LAST_LOOP next
	while :; do
		base=/dev/loop$i
		next=$((i + 1))

		# If loop device is already set to other file
		if losetup "$base" >/dev/null 2>&1; then
			i=$next
			continue
		fi

		# If loop device fails to setup
		if ! losetup "$base" "$1" >/dev/null 2>&1; then
			i=$next
			continue
		fi

		# Assign to global variable _LAST_LOOP
		export _LAST_LOOP=$next

		ln -s "$base" /dev/block

		if [ "$2" ]; then
			mknod "$2" b 7 $((i * 16))
		else
			export RESULT=$i
		fi

		return 0
	done
}

auto_partition() {
	[ "$OEM_INSTALL" = "force" ] || [ "$OEM_INSTALL" = "mbr" ] || [ "$OEM_INSTALL" = "efi" ] || dialog --title " OEM Installer " --defaultno --yesno \
		"\nYou have chosen the OEM installation.\n\nThe installer will erase the whole \"/dev/$1\" and install $OS_TITLE to it.\n\nThis is the last confirmation. Are you sure to do so?" 12 61 ||
		rebooting

	local p
	if [ ! "$EFI" ] || [ "$OEM_INSTALL" = "mbr" ]; then
		if echo -e "o\nn\np\n1\n\n\nw\n" | fdisk "/dev/$1"; then
			echo 'FDISK: Partition created with fdisk'
			p=1
		elif
			sfdisk --delete "/dev/$1"
			sfdisk -a -X linux "/dev/$1"
		then # TRY
			echo 'SFDISK: Partition created with sfdisk'
			p=1
		else # CATCH
			echo 'SGDISK: Using sgdisk to create and convert to mbr instead'
			sgdisk --zap-all "/dev/$1"
			sgdisk --new=1::+500M --typecode=1:EF00 --largest-new=2 --typecode=2:8300 "/dev/$1"
			local plist
			plist=$(sgdisk --print "/dev/$1" | awk '/^  / { printf "%s:", $1 }' | sed 's/:$//')
			sgdisk --gpttombr="$plist" "/dev/$1" >/dev/tty6
			p=2
			until try_mount rw "/dev/$1" $DEST; do sleep 1; done
		fi
	elif [ "$OEM_INSTALL" = "efi" ]; then
		sgdisk --zap-all "/dev/$1"
		sgdisk --new=1::+500M --typecode=1:EF00 --largest-new=2 --typecode=2:8300 "/dev/$1"
		p=2
	else
		sgdisk --zap-all "/dev/$1"
		sgdisk --new=1::+500M --typecode=1:EF00 --largest-new=2 --typecode=2:8300 "/dev/$1"
		p=2
	fi >/dev/tty6

	while sleep 1; do
		answer=$(find_partition "$1" "$p")
		[ "$answer" ] && break
	done
	export answer

	if [ "$EFI" ] || [ "$OEM_INSTALL" = "efi" ]; then
		mkdosfs -n EFI -F 32 "/dev/$(find_partition "$1" 1)"
	fi
}

partition_drive() {
	echo -n >$menufile
	local i f sz
	for i in "${LIST_DISK[@]}"; do
		echo -n "$(basename "$i")" >>$menufile
		if [ -f "$i/removable" ] && [ "$(cat "$i/removable")" = 0 ]; then
			echo -n ' "Harddisk ' >>$menufile
		else
			echo -n ' "Removable' >>$menufile
		fi
		if [ -f "$i/size" ]; then
			sz=$(size_gb "$i")
			[ "$sz" = "0.00GB" ] && sz="<0.01GB"
			printf " %10s" "$sz" >>$menufile
		fi
		for f in "$i"/device/model "$i"/*/name; do
			[ -e "$f" ] && echo -n " $(sed $'s/\x04//g' "$f")" >>$menufile && break
		done
		echo '"' >>$menufile
	done

	local count
	count=$(wc -l <$menufile)
	if [ "$count" = 0 ]; then
		dialog --title " Error " --msgbox \
			"\nOK. There is no hard drive to edit partitions." 8 49
		return 255
	fi

	local drive
	if [ "$count" = 1 ] || [ "$OEM_INSTALL" = "force" ] || [ "$OEM_INSTALL" = "mbr" ] || [ "$OEM_INSTALL" = "efi" ]; then
		drive=1
	else
		drive=$(basename "$OEM_INSTALL")
	fi

	CHOICE=$(awk -v "n=$drive" '{ if (n == NR || n == $1) print $1 }' $menufile)
	export CHOICE
	if [ -b "/dev/$CHOICE" ]; then
		export RET=0
	else
		choose "Choose Drive" "Please select a drive to edit partitions:\n\n* - Installer source"
	fi
	if [ $RET = 0 ]; then
		if [ "$OEM_INSTALL" ]; then
			auto_partition "$CHOICE"
			return 1
		fi
		local part_tool
		if fdisk -l "/dev/$CHOICE" | grep -q GPT; then
			part_tool=cgdisk
		elif fdisk -l "/dev/$CHOICE" | grep -q "doesn't"; then
			dialog --title " Confirm " --defaultno --yesno \
				"\n The setup will now redirect to the cfdisk program on drive /dev/$CHOICE. \
However, would you prefer to use the cgdisk program instead? \
\n cgdisk is designed exclusively for GPT disks, while cfdisk can handle both MBR and GPT. \
This is merely a preference; if you wish, we can redirect to cgdisk instead. \
Select 'Yes' to switch to cgdisk, or 'No' to remain with cfdisk. \
\n \
\n Tips : If you install on a VM or on a fresh new drive, on cfdisk 'dos' is for MBR, 'gpt' is for GPT" 16 60 &&
				part_tool=cgdisk || part_tool=cfdisk
		else
			part_tool=cfdisk
		fi

		if $part_tool "/dev/$CHOICE"; then
			export RET=1
		else
			export RET=255
		fi
	fi
	return $RET
}

select_dev() {
	blkid | grep -Ev "^/dev/block/|^/dev/loop" | cut -b6- | sort | awk '{
		l=""
		t="unknown"
		sub(/:/, "", $1)
		for (i = NF; i > 1; --i)
			if (match($i, "^TYPE")) {
				t=$i
				gsub(/TYPE=|"/, "", t)
			} else if (match($i, "^LABEL")) {
				l=$i
				gsub(/LABEL=|"/, "", l)
			}
		printf("%-11s%-12s%-18s\n", $1, t, l)
	}' >$tempfile

	printf '' >$menufile
	local d i f sz m n
	for d in "${LIST_DISK[@]}"; do
		m="$(cat "${d}/device/model")"
		n="$(cat "${d}/device/name")"

		find "${d}/" -mindepth 1 -maxdepth 1 -type d -iname "$(basename "$d")*" | while read -r i; do
			f=$(grep "$(basename "$i")" $tempfile || printf "%-11s%-30s" "$(basename "$i")" unknown)

			sz=$(size_gb "$i")
			((${sz%.*} > ${MIN_PT_SIZE%GB})) || continue

			printf "\"$f%10s\" \"%-17s\"\n" "$sz" "$m $n" >>$menufile
		done
	done
	printf "\"\" \"\"\n\"Create/Modify partitions\" \"\"\n\"Detect devices\" \"\"\n\"Open command-line shell\" \"\"" >>$menufile
	choose "Choose Partition" "Please select a partition to install $OS_TITLE:\n\nRecommended minimum free space - 8GB  |  Optimum free space >= 16GB\n\nPartition | Filesystem | Label            | Size     | Drive name/model"
	return $RET
}

progress_bar() { dialog --clear --title " \"$1\" " --gauge "\n \"$2\"" 8 70; }

convert_fs() {
	if blkid "/dev/$1" | grep -q ext2; then
		tune2fs -j "/dev/$1"
		e2fsck -fy "/dev/$1"
	fi
	if blkid "/dev/$1" | grep -q ext3; then
		tune2fs -O extents,uninit_bg "/dev/$1"
		e2fsck -fy "/dev/$1"
	fi
}

format_fs() {
	local cmd
	echo -e '"Do not re-format" ""\next4 ""\nntfs ""\nfat32 ""\nexfat ""\nf2fs ""' >$menufile
	set_answer_if_auto "$FORCE_FORMAT"
	choose "Choose filesystem" "Please select a filesystem to format \"$1\":"
	case "$CHOICE" in
	ext4) cmd="mkfs.ext3 -L" ;;
	exfat) cmd="mkfs.exfat -L" ;;
	f2fs) cmd="make_f2fs -l" ;;
	ntfs) cmd="mkfs.ntfs -fL" ;;
	fat32) cmd="mkdosfs -F 32 -n" ;;
	*) ;;
	esac
	if [ "$cmd" ]; then
		[ "$OEM_INSTALL" ] ||
			dialog --title " Confirm " --defaultno --yesno \
				"\n You chose to format \"$1\" to $CHOICE.\n All data in that partition will be LOST.\n\n Are you sure to format the partition \"$1\"?" 10 59 ||
			return 1
		$cmd "$OS_TITLE" "/dev/$1" | awk '{
			# FIXME: very imprecise progress
			if (match($0, "done"))
				printf("%d\n", i+=33)
		}' | progress_bar "Formatting" "Formatting partition \"$1\"..."
		convert_fs "$1" >$LOG
	elif blkid "/dev/$1" | grep -q 'ext[23]'; then
		dialog --clear --title " Warning " --yesno \
			"\nYou chose to install android-x86 to an ext2/3 filesystem. We suggest you convert it to ext4 for better reliability and performance." 9 62 &&
			convert_fs "$1" >$LOG
	fi
}

try_upgrade() {
	[ ! -f "${1}/fstab.android" ] && dialog --title "No install found to upgrade at: \"$1\"" --nocancel --pause "" 8 54 1 && return

	rm -rf "$1"/data/dalvik-cache/* "$1"/data/system/wpa_supplicant
	[ -s "$1"/data/misc/wifi/wpa_supplicant.conf ] && sed -i 's/\(ctrl_interface=\)\(.*\)/\1wlan0/' "$1"/data/misc/wifi/wpa_supplicant.conf
}

get_part_info() {
	local d=0 h part
	while :; do
		h=$(echo $d | awk '{ printf("%c", $1+97) }')
		for part in /sys/block/[shv]d"$h"/"$1" /sys/block/xvd"$h"/"$1" /sys/block/mmcblk"$d"/"$1" /sys/block/nvme0n$((d + 1))/"$1"; do
			[ -d "$part" ] && break 2
		done
		d=$((d + 1))
	done
	DISK=$(basename "$(dirname "$part")")
	export DISK
}

wait_for_device() {
	local t
	t=$(echo /sys/block/*/"$1")
	[ -f "$t/partition" ] || return 1
	until [ -b "/dev/$1" ]; do
		echo add >"$t/uevent"
		sleep 1
	done
}

install_to() {
	wait_for_device "$1" || return 1
	cd /
	mountpoint $DEST && umount $DEST
	[ "$AUTO_UPDATE" ] && FORCE_FORMAT=no || FORCE_FORMAT=ext4
	export FORCE_FORMAT
	while :; do
		format_fs "$1"
		try_mount rw "/dev/$1" $DEST && break
		dialog --clear --title " Error " --defaultno --yesno \
			"\n Cannot mount /dev/$1\n Do you want to format it?" 8 37 ||
			return 255
		FORCE_FORMAT=ext4
		export FORCE_FORMAT
	done

	[ "$INSTALL_PREFIX" ] && A_SRC=$INSTALL_PREFIX || A_SRC=
	export A_SRC

	CMDLINE="$(cat /cdrom/cmdline.txt) SRC=$A_SRC" # androidboot.slot_suffix=_a androidboot.mode=normal
	export CMDLINE

	# shellcheck disable=SC1091
	. $SCRIPT_DIR/grub_modules

	local add_args=
	if [ -d /usr/share/grub/themes ]; then
		local theme
		theme=$(find /usr/share/grub/themes -mindepth 1 -maxdepth 1 -type d -print -quit)
		[ "$theme" ] && add_args="$add_args --themes=$(basename "$theme")"
	fi

	set_answer_if_auto 1
	if { [ ! "$EFI" ] || [ "$OEM_INSTALL" = "mbr" ]; } &&
		adialog --title " Confirm " --no-label Skip --defaultno --yesno \
			"\n Do you want to install boot loader GRUB?" 7 47; then

		get_part_info "$1"
		if fdisk -l "/dev/$DISK" | grep -q GPT; then
			umount $DEST
			dialog --title " Warning " --defaultno --yesno \
				"\nFound GPT on /dev/$DISK. The legacy GRUB can't be installed to GPT. Do you want to convert it to MBR?\n\nWARNING: This is a dangerous operation. You should backup your data first." 11 63 ||
				rebooting
			local plist
			plist=$(sgdisk --print "/dev/$DISK" | awk '/^  / { printf "%s:", $1 }' | sed 's/:$//')
			sgdisk --gpttombr="$plist" "/dev/$DISK" >/dev/tty6

			until try_mount rw "/dev/$1" $DEST; do
				sleep 1
			done
		fi

		# shellcheck disable=SC2086
		grub-install \
			--target=i386-pc \
			--boot-directory="$DEST/$A_SRC/boot" \
			$add_args \
			-v \
			"/dev/$DISK" >$LOG ||
			return 255
	fi

	if [ "$EFI" ] && [ "$OEM_INSTALL" != "mbr" ] &&
		adialog --title " Confirm " --no-label Skip --yesno \
			"\n Do you want to install EFI GRUB2?" 7 39; then

		local esp
		[ ! "$OEM_INSTALL" ] || [ "$AUTO_UPDATE" ] &&
			for i in "${LIST_DISK[@]}"; do
				DISK=$(basename "$i")
				esp=$(sgdisk --print "/dev/$DISK" 2>/dev/null | grep EF00 | awk '{print $1}')
				[ "$esp" ] && boot=$(find_partition "$DISK" "$esp") && break
			done

		if [ ! "$esp" ]; then
			get_part_info "$1"
			boot=$(blkid "/dev/$DISK"* | grep -v "$DISK:" | grep vfat | cut -d: -f1 | head -1)
			[ ! "$boot" ] && boot=$(find_partition "$DISK" 1) || boot=$(basename "$boot")
			esp=$(cat "/sys/block/$DISK/$boot/partition")
		fi

		mkdir -p $DEST/boot/efi
		cd $DEST/boot

		mountpoint efi && umount efi
		wait_for_device "$boot"
		until try_mount rw "/dev/$boot" efi; do
			dialog --title " Confirm " --defaultno \
				--yesno "\n Cannot mount /dev/$boot.\n Do you want to format it?" 8 37 &&
				mkdosfs -n EFI -F 32 "/dev/$boot"
		done

		if [ 0 = "$(df efi | tail -1 | awk '{ print $4 }')" ]; then
			if dialog --title " Confirm " --defaultno \
				--yesno "\n /dev/$boot is full.\n Do you want to format it?" 8 37; then
				umount -f efi && sleep 1 # wait for sync
				mkdosfs -n EFI -F 32 "/dev/$boot"
				until try_mount rw "/dev/$boot" efi; do
					sleep 1
				done
			fi
		fi

		if [ "$(cat "/sys/block/$DISK/removable")" = 1 ]; then
			add_args="$add_args --removable"
		fi

		local efi_arch grub_target
		if [ "$EFI" = "32" ]; then
			grub_target=i386
			efi_arch=ia32
		else
			grub_target=x86_64
			efi_arch=x64
		fi

		# shellcheck disable=SC2086
		grub-install \
			--target=$grub_target-efi \
			--efi-directory=efi \
			--boot-directory="$DEST/$A_SRC/boot" \
			--bootloader-id=$BOOT_ID \
			--no-nvram \
			$add_args \
			-v \
			"/dev/$DISK" >$LOG ||
			return 255

		local efidir=efi/$BOOT_ID
		local bootefi=$efidir/grub$efi_arch.efi

		# copy to default efi
		local default_entry=efi/efi/boot/boot$efi_arch.efi
		if [ ! -e $default_entry ]; then
			mkdir -p efi/efi/boot
			cp efi/$bootefi $default_entry
		fi

		CMDLINE="$CMDLINE androidboot.efidir=/boot/efi/$efidir androidboot.efidisk=$boot"
		export CMDLINE

		# Checking for old EFI entries, removing them and adding new depending on bitness
		efibootmgr | grep -Eo ".{0,6}$BOOT_ID" | cut -c1-4 >/tmp/efientries
		if [ -s /tmp/efientries ]; then
			set_answer_if_auto 1
			adialog --title " Question " --yesno "\nEFI boot entries for previous $OS_TITLE installations were found.\n\nDo you wish to delete them?" 10 61 &&
				while read -r entry; do efibootmgr -Bb "$entry" >/dev/tty4 2>&1; done </tmp/efientries
		fi
		# Check if the entry has been created, if not, it may due to the efivar got full
		# Remove all /sys/firmware/efi/efivars/dump-* and run the command again
		if efibootmgr -u -v -c -d "/dev/$DISK" -p "$esp" -L "$BOOT_ID" -l /$bootefi >/dev/tty4 2>&1 &&
			! efibootmgr | grep -q "$BOOT_ID"; then
			rm -rf /sys/firmware/efi/efivars/dump-*
			efibootmgr -u -v -c -d "/dev/$DISK" -p "$esp" -L "$BOOT_ID" -l /$bootefi >/dev/tty4 2>&1
		fi

		if [ -s efi/startup.nsh ]; then
			sed -i "s|\\\\efi\\\\Android|$efidir|; s|/|\\\\|g" efi/startup.nsh
		else
			echo $efidir/$bootefi | sed 's|/|\\|g' >efi/startup.nsh
		fi

		cd /
	fi

	if [ "$OEM_INSTALL" = "force" ] || [ "$OEM_INSTALL" = "mbr" ] || [ "$OEM_INSTALL" = "efi" ]; then
		echo "OEM install forcing is enabled, skipping upgrade..."
	else
		try_upgrade "$DEST/$A_SRC"
	fi

	! test -f "$DEST/$A_SRC/system.img" -o -d "$DEST/$A_SRC/system"

	declare -a files=(
		"/cdrom/$SRC/kernel"
		"/cdrom/$SRC/initrd.img"
		"/cdrom/$SRC/ramdisk-recovery.img"
		/source/system.img
	) dests=(
		kernel
		initrd.img
		recovery.img
		system.img
	) sizes=(
		36
		20
		40
		5120
	)

	find "$DEST/$A_SRC" \( -iname "system*" -o -iname "*.img" \) -exec rm -rf {} +
	mkdir -p "$DEST/$A_SRC"

	local i source target target_type
	for i in $(seq 0 $((${#files[@]} - 1))); do
		source="${files[$i]}"
		target="${dests[$i]}"

		target_type=.${target##*.}
		[ "$target_type" = ".$target" ] && target_type=

		bash $SCRIPT_DIR/make-ab "$DEST/$A_SRC/$target" "${sizes[$i]}"
		{
			pv -n -s "$(du -sb "$source" | cut -f1)" "$source" |
				dd of="$DEST/$A_SRC/${target%.*}_a${target_type}" bs=4M conv=notrunc 2>/dev/null
		} 2>&1 | progress_bar "Installing $OS_TITLE to \"$1\"" "Expect to write $source ${sizes[$i]} KB..." ||
			return 1
	done

	cd "$DEST/$A_SRC"
	for d in android mnt sfs ./"$SRC"; do
		[ -d "$d" ] && mv "$d"/* . && rmdir "$d"
	done
	chown 0.0 ./*
	for f in ./*; do
		[ -d "$f" ] || chmod 644 "$f"
	done
	cd /

	dialog --infobox "\n Preparing install for A/B updates..." 5 42
	bash $SCRIPT_DIR/gen-img "$DEST/$A_SRC"
	local data_type
	[ -f "$DEST/$A_SRC/data.img" ] && data_type=.img
	cat <<EOF >"$DEST/$A_SRC/fstab.android"

\$FS/system\$SLOT.img	system\$SLOT
\$FS/kernel\$SLOT	kernel\$SLOT
\$FS/initrd\$SLOT.img	initrd\$SLOT
\$FS/recovery\$SLOT.img	recovery\$SLOT

\$FS/boot	bootloader
\$FS/misc.img	misc
\$FS/data${data_type}	userdata	auto	defaults	defaults

$(bash $SCRIPT_DIR/genfstab -U "$DEST/$A_SRC")

$([ "$EFI" ] && echo "none	/sys/firmware/efi/efivars	efivarfs  defaults	defaults")
EOF

	dialog --infobox "\n Configuring bootloader..." 5 30
	CONF_PREFIX=$DEST/$A_SRC/boot/grub
	export CONF_PREFIX
	sed -i "s|_grub_themes_dir_placeholder|$CONF_PREFIX/themes|g" /etc/default/grub
	grub-mkconfig -o "$CONF_PREFIX/grub.cfg"
	cat <<EOF >>"$CONF_PREFIX/android.cfg"
SLOT=_a
CMDLINE="$CMDLINE"
MODE=normal
EOF
	grub-editenv "$CONF_PREFIX/grubenv" create || :
	setenv() { grub-editenv "$CONF_PREFIX/grubenv" set "$@" >&2; }
	{
		setenv pixel_format="RGBX_8888"
		setenv ui_mode="BASS_TABLETUI=1"
		setenv HYBRID_PC_MODE=0
		setenv bliss_bootmode=
		setenv DESKTOP_ON_EXTERNAL=0
		setenv win_as_home=1
		setenv per_display_focus="androidboot.per_display_focus_enabled=true"
		setenv external_input=0
		setenv external_touch="FORCE_IME_ON_SECONDARY_DISPLAYS=1"
		setenv NAVIGATION="FORCE_DISABLE_NAVIGATION=false FORCE_DISABLE_NAV_HANDLE=false FORCE_DISABLE_NAV_TASKBAR=false"
		setenv MOUSE_PRESENTATION=1
		setenv animation_scale="androidboot.bliss.window.animation.scale=0.1"
		setenv FFMPEG_CODEC2_PREFER=1
		setenv FFMPEG_OMX_CODEC=0
	}

	dialog --infobox "\n Syncing to disk..." 5 27
	sync

	return 0
}

install_hd() {
	case "$OEM_INSTALL" in
	[Uu]*)
		answer=${AUTO_UPDATE:-"$(blkid | grep -v loop | grep -v iso9660 | sort | grep "$OS_TITLE" | cut -d: -f1 | head -1)"}
		answer=${answer:-"$(blkid | grep -v loop | sort | grep ext4 | cut -d: -f1 | head -1)"}
		[ -b "$answer" ] || [ -b "/dev/$answer" ] && answer=$(basename "$answer") || answer=
		AUTO_UPDATE=${answer:-$AUTO_UPDATE}
		[ "$AUTO_UPDATE" ] || OEM_INSTALL=
		export answer AUTO_UPDATE OEM_INSTALL
		;;
	*)
		[ "$answer" ] || set_answer_if_auto Create
		;;
	esac

	list_disks

	select_dev || rebooting
	export RET=1
	# shellcheck disable=SC2086
	case "$CHOICE" in
	Create*)
		partition_drive
		return $?
		;;
	Detect*) dialog --title " Detecting... " --nocancel --pause "" 8 41 1 ;;
	*shell*) dialog --clear --title " WARNING " --nocancel --pause \
		"You are going to use AOSP's shell, if you want to go back to the installer please type exit" 12 41 8 &&
		debug_shell ;;
	*)
		install_to $CHOICE
		return $?
		;;
	esac
	return $RET
}

do_install() {
	BOOTED_FROM=$(basename "$(find_device "$ROOT")")
	[ "$COPYTORAM" ] && grep -Eq '(tmpfs|none) /cdrom tmpfs' /proc/mounts &&
		BOOTED_FROM=tmpfs ISO_UNPLUGGED=1
	[ "$BOOTED_FROM" ] || BOOTED_FROM=unknown
	EFI=$(cat /sys/firmware/efi/fw_platform_size 2>/dev/null)
	export BOOTED_FROM EFI

	[ "$AUTO_INSTALL" ] && [ ! "$OEM_INSTALL" ] &&
		OEM_INSTALL=$AUTO_INSTALL

	until install_hd; do
		if [ $RET = 255 ]; then
			dialog --title ' Error! ' --yes-label Retry --no-label Reboot \
				--yesno "\nInstallation failed! Either there's no more free space or something is wrong with the installer !" 8 51 ||
				rebooting
		fi
	done

	dialog --title " Installation completed! " --no-cancel --pause \
		"\n\n$([ "$ISO_UNPLUGGED" ] || printf "Please unplug the installation media. \n\n")Press any key to reboot." 12 48 30

	rebooting
}

do_install
