#!/usr/bin/bash

#
# Copyright (C) 2024 Shadichy <shadichy@blisslabs.org>
#
# License: GNU Public License v2 or later
#

function map_device_link() {
  # shellcheck disable=2012,2046
  mknod /dev/block/by-name/"${1#'#>'}" b "$2" "$3"
}

function init_loop_links() {
  mkdir -p /dev/block/by-name

  while read -r line; do
    # shellcheck disable=SC2086
    case "$line" in
    '#>'*) map_device_link $line ;;
    *) ;;
    esac
  done </etc/fstab

  # Handle for misc symlink specifically
  mv /dev/block/by-name/misc /dev/block/by-name/misc-device
  ln -s misc-device /dev/block/by-name/misc
}

init_loop_links
