#!/bin/bash
#
# By Shadichy <shadichy@blisslabs.org>
# Last updated 2026/04/12
#
# License: GNU Public License
# We explicitly grant the right to use the scripts
# with Android-x86 project.
#

export PATH=/sbin:/bin:/system/bin:/system/xbin:/vendor/bin:/system_ext/bin:/system/vendor/bin:/system/system_ext/bin
export SCRIPT_DIR=/usr/share/scripts

##########################################
### THIS SCRIPT RUNS AFTER SWITCH_ROOT ###
##########################################

# override /bin/sh
/bin/busybox ln -s bash /bin/sh

# let busybox install all applets as symlinks
/bin/busybox --install -s /bin

busybox mount -t proc proc /proc
busybox mount -t sysfs sys /sys
busybox mount -t tmpfs tmpfs /tmp

# initialise /dev (first time)
busybox mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/block
echo /bin/mdev >/proc/sys/kernel/hotplug
mdev -s

# initialize file descriptors at /dev
ln -s /proc/self/fd /dev/fd

# First, chmod /usr/bin because somehow the build process messed up the permission
chmod -R 755 /usr/bin

# configure debugging output
LOG=/tmp/log
set -x
exec 2>>$LOG

# shellcheck disable=SC2013
for c in $(cat /proc/cmdline); do
	case "$c" in
	*=*)
		var_name=${c%%=*}
		var_name=${var_name//./__}
		var_name=${var_name//\//__}
		var_value=${c#*=}
		eval export "$var_name"="$var_value"
		;;
	*) ;;
	esac
done

# "foo" as mount source is given to workaround a Busybox bug with NFS
# - as it's ignored anyways it shouldn't harm for other filesystems.
mount -o remount,rw foo /

ln -s android/system android/vendor /
ln -s /vendor/firmware /system/lib/modules /lib
mkdir -p /lib/modules
ln -s /system/lib/modules /lib/modules/"$(uname -r)"

busybox modprobe -a hid-apple

# fstab
bash $SCRIPT_DIR/map-fstab
mount -a

# install
# shellcheck disable=SC2093
bash $SCRIPT_DIR/00_install 2>>$LOG

# avoid kernel panic
while :; do
	echo
	echo '	Android-x86 console shell. Use only in emergencies.'
	echo
	bash
done
